ismlar = ['asilbek',
           'amirjon',
             'anvar', 
             'ashrafjon',
               'axror',
                 'avaz',
                   'ahmad',
                     'alisher',
                       'ayubjon',
                         'abdunabi',
                           'abdulla','bobur',
                             'bahrom',
                               'baxtiyor',
                                 'baxtinur',
                                   'baxtishod', 'bobomurod', 
                                   'bekmurod', 'dilshod', 'diyorbek',
                                     'azizjon','baxtigul', 'bahodir', 'aziza', 
                                     'azamat', 'ulugbek', 'shohjahon', 'mahliyo', 
                                     'daler', 'iftixor', 'ozodbek', 'shahriyor', 'marjona',
                                       'shabnam', 'shohruh', 'sherali', 'shermat', 'mamur', 
                                       'mansur', 'shohsanam', 'gulsanam', 'parizoda', 'elmira','ruhshona','barno','raisa',
                    'norgul','lola','izzatillo','inyatillo','tursinboy','ruziqul','orziqul','hayotjon','shehroz','kamola','elchinbek',
                    'eldor','iroda','rayhona','asila','xudoyberdi','dilbar','doston','farzona','mustafo','umidjon','sitora',
                    'murodjon','mexribon','guzal','botir','sardor','shaxzoda','farida','shohista','samira','shaxina','shaxrina','zulfiqor',
                'oybek','umidjon','tohir', 'nortoy', 'asd', 'ad', 'dilnura', 'madina', 'elyor', 'ilyoz', 'giyoz', 'mumin', 'kozim', 'nozim',
                  'ravshanbek', 'edes', 'doniyor', 
                  'shaxruz', 'shoxinur', 'umurzoq', 'shalola', 'sanobar', 
                  'begzod', 'rahmatjon', 'sherali', 'ilhom', 'samandar', 'abbos', 'abdulaziz', 'abror',
                    'akbar', 'aktamjon', 'behruz', 'beksulton', 'damir', 'davlat', 'doniyor', 'farrux', 'fayoz', 
                    'fayzulla', 'feruz', 'firdavs', 'ganisher', 'gulnora', 'gulshoda', 'gulnoza', 'hasan', 'husan', 'scs', 'fdsa', 
                    'jafar', 'zafar', 'jmshid', 'jahongir', 'javohir', 'jurabek', 'jonibek', 'usmonbek', 'valiya', 
                    'yusuf', 'zamira', 'zarima', 'umida']